---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required  packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: network_pkgs
  when: ansible_os_family == 'RedHat'

- name: Create the network configuration file for ethernet devices
  template: src=ethernet_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.device }}
  with_items: network_ether_interfaces
  when: network_ether_interfaces is defined
  register: ether_result

- name: Write configuration files for rhel route configuration
  template: src=route_{{ ansible_os_family }}.j2 dest={{ net_path }}/route-{{ item.device }}
  with_items: network_ether_interfaces
  when: network_ether_interfaces is defined and item.route is defined and ansible_os_family == 'RedHat'

- shell: ifdown {{ item.item.device }}; ifconfig {{ item.item.device }} down; ifup {{ item.item.device }}
  with_items: ether_result.results
  when: restart_network and ether_result is defined and item.changed

# TODO: Make this template read the config from the definition.
- name: Add the bonding driver config
  template: src=bonding.conf.j2 dest=/etc/modprobe.d/bonding.conf

- name: Make sure the bonding module is loaded
  modprobe: name=bonding state=present
  when: network_bond_interfaces is defined

